theme: jekyll-theme-slate
title: Welcome To Lulamile Portfolio Website
logo: favicon.png
content: UX/UI Designer
description: My UX/UI Designer Portfolio website. Acting at the fulcrum of aesthetics and sustainability to craft experiences both online and in real life whilst conceptualizing,crafting mainly Mobile/Web & any digital products from Product Strategy, Prototyping, Interface Design, Frontend-Development,etc
